<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $set->set_name }}</title>
    <style>
        body {
            font-family: 'nikosh', 'SolaimanLipi', sans-serif;
            font-size: 14pt;
            line-height: 1.6;
            color: #000;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .exam-name {
            font-size: 20pt;
            font-weight: bold;
            text-transform: uppercase;
            margin-bottom: 5px;
        }
        .subject-name {
            font-size: 16pt;
            margin-bottom: 15px;
        }
        .info-box {
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;
            padding: 10px 0;
            margin-top: 20px;
            width: 100%;
        }
        .info-left {
            float: left;
            width: 50%;
        }
        .info-right {
            float: right;
            width: 50%;
            text-align: right;
        }
        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }
        .instructions {
            margin-top: 20px;
            font-size: 11pt;
            text-align: left;
        }
        .question-container {
            margin-top: 40px;
            page-break-inside: avoid;
        }
        .question-number {
            float: left;
            width: 5%;
            font-weight: bold;
        }
        .question-content {
            float: left;
            width: 95%;
        }
        .stem {
            margin-bottom: 15px;
            text-align: justify;
        }
        .sub-questions-table {
            width: 100%;
            border-collapse: collapse;
        }
        .sub-q-text {
            width: 90%;
            padding: 3px 0;
        }
        .sub-q-marks {
            width: 10%;
            text-align: right;
            padding: 3px 0;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 9pt;
            color: #666;
            border-top: 0.5px solid #ccc;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="exam-name">{{ $set->exam_name }}</div>
        <div class="subject-name">{{ $set->subject->subject_name }}</div>
        
        <div class="info-box clearfix">
            <div class="info-left">
                <strong>সময়:</strong> {{ $set->duration_minutes }} মিনিট
            </div>
            <div class="info-right">
                <strong>পূর্ণমান:</strong> {{ $set->total_marks }}
            </div>
        </div>

        @if($set->instructions)
        <div class="instructions">
            <strong>নির্দেশনা:</strong> {{ $set->instructions }}
        </div>
        @endif
    </div>

    <div class="body">
        @foreach($set->questions->sortBy('pivot.question_order') as $question)
            <div class="question-container clearfix">
                <div class="question-number">{{ $loop->iteration }}.</div>
                <div class="question-content">
                    <div class="stem">{!! nl2br(e($question->question_stem)) !!}</div>
                    
                    <table class="sub-questions-table">
                        <tr>
                            <td class="sub-q-text">ক) {{ $question->sub_question_a }}</td>
                            <td class="sub-q-marks">{{ intval($question->sub_question_a_marks) }}</td>
                        </tr>
                        <tr>
                            <td class="sub-q-text">খ) {{ $question->sub_question_b }}</td>
                            <td class="sub-q-marks">{{ intval($question->sub_question_b_marks) }}</td>
                        </tr>
                        <tr>
                            <td class="sub-q-text">গ) {{ $question->sub_question_c }}</td>
                            <td class="sub-q-marks">{{ intval($question->sub_question_c_marks) }}</td>
                        </tr>
                        @if($question->sub_question_d)
                        <tr>
                            <td class="sub-q-text">ঘ) {{ $question->sub_question_d }}</td>
                            <td class="sub-q-marks">{{ intval($question->sub_question_d_marks) }}</td>
                        </tr>
                        @endif
                    </table>
                </div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        Generated by StudentPortal Creative Question System | Page <span class="pagenum"></span>
    </div>
</body>
</html>
