@extends('layouts.admin')

@section('title', 'Set Preview')

@section('content')
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-12 d-flex justify-content-between align-items-center">
            <div>
                <h2>👁️ Exam Paper Preview</h2>
                <p class="text-muted">Set: {{ $set->set_name }} | Subject: {{ $set->subject->subject_name }}</p>
            </div>
            <div class="d-print-none">
                <button onclick="window.print()" class="btn btn-primary">
                    🖨️ Print Preview
                </button>
                @if($set->status == 'published')
                <a href="{{ route('admin.cq.sets.pdf', $set->id) }}" class="btn btn-danger">
                    📥 Download PDF
                </a>
                @endif
                <a href="{{ route('admin.cq.sets.edit', $set->id) }}" class="btn btn-outline-secondary">
                    ← Back to Edit
                </a>
            </div>
        </div>
    </div>

    <!-- The Exam Paper -->
    <div class="card border-0 shadow-sm mx-auto" style="max-width: 800px; padding: 40px; background-color: white;">
        <div class="exam-header text-center mb-5">
            <h2 class="mb-1 text-uppercase">{{ $set->exam_name }}</h2>
            <h4 class="mb-2">{{ $set->subject->subject_name }}</h4>
            <div class="d-flex justify-content-between border-top border-bottom py-2 mt-4">
                <div>
                    <strong>Time:</strong> {{ $set->duration_minutes }} minutes
                </div>
                <div>
                    <strong>Full Marks:</strong> {{ $set->total_marks }}
                </div>
            </div>
            @if($set->instructions)
            <div class="mt-4 text-start small">
                <strong>Instructions:</strong> {{ $set->instructions }}
            </div>
            @endif
        </div>

        <div class="exam-body">
            @forelse($set->questions->sortBy('pivot.question_order') as $question)
                <div class="question-container mb-5">
                    <div class="d-flex">
                        <div class="fw-bold pe-2">{{ $loop->iteration }}.</div>
                        <div class="flex-grow-1">
                            <div class="question-stem mb-3 text-justify">
                                {!! nl2br(e($question->question_stem)) !!}
                            </div>
                            
                            <div class="sub-questions ps-3">
                                <div class="row mb-1">
                                    <div class="col-10">ক) {{ $question->sub_question_a }}</div>
                                    <div class="col-2 text-end">{{ intval($question->sub_question_a_marks) }}</div>
                                </div>
                                <div class="row mb-1">
                                    <div class="col-10">খ) {{ $question->sub_question_b }}</div>
                                    <div class="col-2 text-end">{{ intval($question->sub_question_b_marks) }}</div>
                                </div>
                                <div class="row mb-1">
                                    <div class="col-10">গ) {{ $question->sub_question_c }}</div>
                                    <div class="col-2 text-end">{{ intval($question->sub_question_c_marks) }}</div>
                                </div>
                                @if($question->sub_question_d)
                                <div class="row mb-1">
                                    <div class="col-10">ঘ) {{ $question->sub_question_d }}</div>
                                    <div class="col-2 text-end">{{ intval($question->sub_question_d_marks) }}</div>
                                </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            @empty
                <div class="alert alert-warning text-center">
                    No questions added to this set yet.
                </div>
            @endforelse
        </div>

        <div class="exam-footer text-center mt-5 pt-5 text-muted small border-top d-none d-print-block">
            Generated by StudentPortal CQ System
        </div>
    </div>
</div>

<style>
@media print {
    body * { visibility: hidden; }
    .card, .card * { visibility: visible; }
    .card {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        box-shadow: none !important;
        margin: 0 !important;
        padding: 0 !important;
    }
    .d-print-none { display: none !important; }
}
.question-stem { font-size: 1.1rem; line-height: 1.6; }
.sub-questions { font-size: 1.05rem; }
.text-justify { text-align: justify; }
</style>
@endsection
